
SAMPLES = ["CR_bCat_Lef1_HH3_1-1", "CR_bCat_Lef1_HH3_1-2", "CR_bCat_Lef1_HH3_1-3","CR_bCat_Lef1_HH3_2-1", "CR_bCat_Lef1_HH3_2-2", "CR_bCat_Lef1_HH3_2-3", "CR_bCat_Lef1_HH3_3-1", "CR_bCat_Lef1_HH3_3-2", "CR_bCat_Lef1_HH3_3-3"] 

rule all:
	input:
		expand("fastq/{sample}_R1_fastqc.html", sample=SAMPLES),
		expand("trimmed_fastq/trimmed_{sample}_R1.fastq.gz", sample=SAMPLES),
		expand("trimmed_fastq/trimmed_{sample}_R2.fastq.gz", sample=SAMPLES),
		#expand("logs/cutadapt/{sample}.log", sample=SAMPLES),
		expand("bam/galGal6/{sample}_galGal6.bam", sample=SAMPLES),
		#expand("bam/sacCer3/{sample}_sacCer3.bam", sample=SAMPLES),
		expand("bam/galGal6/{sample}_galGal6.bam.bai", sample=SAMPLES),
		#expand("bam/sacCer3/{sample}_sacCer3.bam.bai", sample=SAMPLES),
		expand("bam/galGal6/dupsMarked/{sample}_galGal6_dupsMarked.bam", sample=SAMPLES),
		expand("peaks/{sample}_peaks.narrowPeak", sample=SAMPLES),
		expand("peaks/nodups/{sample}_peaks.narrowPeak", sample=SAMPLES),
		expand("bw/nodups/{sample}_galGal6_nodups.bw", sample=SAMPLES),
		expand("bw/{sample}_galGal6_dups.bw", sample=SAMPLES),
		expand("bam/galGal6/nodups/{sample}_galGal6_nodups.bam", sample=SAMPLES),
        	expand("bam/galGal6/nodups/{sample}_galGal6_nodups.bam.bai", sample=SAMPLES)


rule fastqc:
	input:
		R1="fastq/{sample}_R1.fastq.gz",
		R2="fastq/{sample}_R2.fastq.gz"
	output:
		R1="fastq/{sample}_R1_fastqc.html",
		R2="fastq/{sample}_R2_fastqc.html"
	threads: 8
	shell:
		"fastqc {input} -t {threads}"


rule cutadapt:
	input:
		R1="fastq/{sample}_R1.fastq.gz",
		R2="fastq/{sample}_R2.fastq.gz"
	output:
		R1="trimmed_fastq/trimmed_{sample}_R1.fastq.gz",
		R2="trimmed_fastq/trimmed_{sample}_R2.fastq.gz"
	log:
		"logs/cutadapt/{sample}.log"
	threads: 8
	shell:
		"cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA \
		-A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT \
		--minimum-length=25 \
		--cores={threads} \
		{input.R1} \
		{input.R2} \
		-o {output.R1} \
		-p {output.R2} 2> {log}"


rule galGal6_bowtie2:
	input:
		R1="trimmed_fastq/trimmed_{sample}_R1.fastq.gz",
		R2="trimmed_fastq/trimmed_{sample}_R2.fastq.gz"
	output:
		bam="bam/galGal6/{sample}_galGal6.bam"
	log:
		"logs/bowtie2/{sample}_galGal6.log"
	threads: 16
	shell:
		"/home/mmr234/Programs/bowtie2-2.4.2-linux-x86_64/bowtie2 --local --very-sensitive-local \
		--no-unal --no-mixed --no-discordant \
		-x /data/Megan/genome_data/gallus_gallus/galGal6_ensembl_bt2/galGal6_ens_bt2 \
		-I 10 -X 1000 \
		-1 {input.R1} \
		-2 {input.R2} \
		--threads {threads} \
		2> {log} | samtools view -F 780 -f 2 -bh - | samtools sort -T {wildcards.sample}_galGal6 - -o {output.bam}"


rule sacCer3_bowtie2:
	input:
		R1="trimmed_fastq/trimmed_{sample}_R1.fastq.gz",
		R2="trimmed_fastq/trimmed_{sample}_R2.fastq.gz"
	output:
		bam="bam/sacCer3/{sample}_sacCer3.bam"
	log:
		"logs/bowtie2/{sample}_sacCer3.log"
	threads: 16
	shell:
		"/home/mmr234/Programs/bowtie2-2.4.2-linux-x86_64/bowtie2 --local --very-sensitive-local \
		--no-unal --no-mixed --no-discordant \
		-x /data/Megan/genome_data/sacCer3_ensembl_bt2/genome \
		-I 10 -X 1000 \
		-1 {input.R1} \
		-2 {input.R2} \
		--threads {threads} \
		2> {log} | samtools view -F 780 -f 2 -bh - | samtools sort -T {wildcards.sample}_sacCer3 - -o {output.bam}" 


rule index_galGal6:
	input:
		"bam/{sample}_galGal6.bam"
	output:
		"bam/{sample}_galGal6.bam.bai"
	shell:
		"samtools index {input}"


rule index_sacCer3:
	input:
		"bam/sacCer3/{sample}_sacCer3.bam"
	output:
		"bam/sacCer3/{sample}_sacCer3.bam.bai"
	shell:
		"samtools index {input}"


rule markDups:
	input:
		bam="bam/galGal6/{sample}_galGal6.bam", 
		bai="bam/galGal6/{sample}_galGal6.bam.bai"
	output:
		bam="bam/galGal6/dupsMarked/{sample}_galGal6_dupsMarked.bam",
		txt="bam/galGal6/dupsMarked/{sample}_dupsMarkedStats.txt"
	shell:
		"java -jar /opt/picard/picard.jar MarkDuplicates \
		I= {input.bam}\
		O= {output.bam}\
		M= {output.txt}"


rule RmDups:
        input:
                "bam/galGal6/dupsMarked/{sample}_galGal6_dupsMarked.bam"
        output:
                "bam/galGal6/nodups/{sample}_galGal6_nodups.bam"
        shell:
                "samtools view -F 1804 -f 2 -b {input} | samtools sort > {output}"

rule index_nodups:
        input:
                "bam/galGal6/nodups/{sample}_galGal6_nodups.bam"
        output:
                "bam/galGal6/nodups/{sample}_galGal6_nodups.bam.bai"
        shell:
                "samtools index {input}"


rule callpeak_dups:
	input:
		"bam/galGal6/{sample}_galGal6.bam"
	output:
		"peaks/{sample}_peaks.narrowPeak"
	log:
		"logs/macs2/{sample}.log"
	shell:
		"macs2 callpeak -t {input} -n {wildcards.sample} -f BAMPE -g 1e9 -q 0.05 --call-summits --outdir ./peaks 2> {log}"


rule callpeak_nodups:
	input:
		"bam/galGal6/nodups/{sample}_galGal6_nodups.bam"
	output:
		"peaks/nodups/{sample}_peaks.narrowPeak"
	log:
		"logs/macs2/{sample}.log"
	shell:
		"macs2 callpeak -t {input} -n {wildcards.sample} -f BAMPE -g 1e9 -q 0.05 --call-summits --outdir ./peaks/nodups 2> {log}"


rule bamCoverage_nodups:
	input:
		bam="bam/galGal6/nodups/{sample}_galGal6_nodups.bam", 
		bai="bam/galGal6/nodups/{sample}_galGal6_nodups.bam.bai"
	output:
		"bw/nodups/{sample}_galGal6_nodups.bw"
	threads: 8
	shell:
		"bamCoverage --bam {input.bam} \
		--outFileName {output} \
		--outFileFormat bigwig \
		--binSize 5 \
		--numberOfProcessors {threads} \
		--normalizeUsing RPKM \
		--extendReads"


rule bamCoverage_dups:
	input:
		bam="bam/galGal6/{sample}_galGal6.bam", 
		bai="bam/galGal6/{sample}_galGal6.bam.bai"
	output:
		"bw/{sample}_galGal6_dups.bw"
	threads: 8
	shell:
		"bamCoverage --bam {input.bam} \
		--outFileName {output} \
		--outFileFormat bigwig \
		--binSize 5 \
		--numberOfProcessors {threads} \
		--normalizeUsing RPKM \
		--extendReads"





